server:
  port: 8879

spring:
  application:
    name: services-config

  ## 配置rabbitMQ 信息
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      trace:
        enabled: true


